language: java
branches:
  only:
  - master
  - "/^v.*$/"
before_deploy:
  - mvn clean install
deploy:
  provider: releases
  api_key:
    secure: "hLc97eLNurWUbe7R+4fkgVilgDhiSPgB3lozkPJP6GBDuMNkupzHgsRS1qmWi9bUtKciw5VdoltqFsOtOXIhEl5xdjQUQiMwHuqEa0UewmCr1oyuvShyISPthYKlyl8HZFuKipdkVC2EpwMK2xS/E97ieTIYXEq+GUzyuUM2G9GTHYfsR0ujhpHjd+5UYmza4//5IQgFRpdk+9GBcY7sf3swUP1/3VKvadbR4von51o2GnFbWpF8BVvw+Zl5xl7UrWzXMtpcI3UTjUdz92JO+DpFkiQG2NjBxtWuCd7smqyCzIGAOUPxXYQ9plV/2GlF78KueJ7Arlxz/sINYb1dyhY5SUgyLRHAihjVOFuWzCoU6s3BZnSdNTcjLPpiwt4mdl9pJ0+ZF9V2faEZYwntt/anIMtK0a1nqoamADTNgxEI+ETrdOFD0UXxUqZqiosbkXXe4Uvdkebcis9jUqgp5qYQl/cuM6zM9gv40xkWRs4O972JHz2HAhFJbSKYaKvyb/uj9UPhWliNVhgmVHwSFgIlaPxFOt49sbboB9GeYiGto4HNd9+HVLu7LsrREV7KTVWl/UKi/tfc23axjliPi6cjwuq4Fi4yHz7kXMq8kJISrrFHP2qluboXRYOlhyoVAVavBF909O28/Le2iuso8GV0H9gVWRbcBnOhhMLRoNc="
  file: "target/hon-lucene-synonyms.jar"
  skip_cleanup: true
  on:
    tags: true
